language: c
dist: trusty
before_install:
  - |
    # Test the master branch with Nim master and other branches with Nim devel
    if [ "$TRAVIS_BRANCH" = master ]; then
        export branch=master
    else
        export branch=devel
    fi
    sudo apt-get update
    sudo apt-get install libpcre3 libpcre3-dev
install:
  - |
    if [ ! -x nim-master/bin/nim ]; then
      # If the Nim executable does not exist (means we haven't installed Nim yet)
      # (do what we did before)
      git clone -b master --depth 1 git://github.com/nim-lang/nim nim-master/
      cd nim-master
      git clone -b master --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
    else
      # We already have the repository, go to it
      cd nim-master
      # Download latest commits from the repository
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        # Recompile Nim (using itself), only if there were new changes
        bin/nim c koch
        ./koch boot -d:release
      fi
    fi
    cd ..
    # export nim
    export PATH="nim-$branch/bin:$PATH"
    git clone --depth 1 https://github.com/nim-lang/nimble.git nimble/
    mkdir lib
    nim c -r nimble/src/nimble install <<< y

script: nim c --run ./tests/test.nim

cache:
  directories:
    - nim-master
    - nim-devel
    - nimble

branches:
  except:
    - gh-pages