language: c
before_install:
  - |
    # Test the master branch with Nim master and other branches with Nim devel
    if [ "$TRAVIS_BRANCH" = master ]; then
        export branch=master
    else
        export branch=devel
    fi
install:
  - |
    git clone -b $branch --depth 1 git://github.com/nim-lang/nim nim-$branch/
    cd nim-$branch
    git clone -b $branch --depth 1 git://github.com/nim-lang/csources csources/
    cd csources
    sh build.sh
    cd ..
    rm -rf csources
    bin/nim c koch
    ./koch boot -d:release
    export PATH="nim-$branch/bin:$PATH"
    cd ..
    git clone --depth 1 https://github.com/nim-lang/nimble.git nimble/
    cd nimble
    nim c -r src/nimble install
    export PATH="~/.nimble/bin:$PATH"
    cd ..

before_script:
  - echo $PATH
  - nimble install
script: nim c --run ./tests/test.nim

cache:
  directories:
    - nim-master
    - nim-devel
    - nimble

branches:
  except:
    - gh-pages