language: c
before_install:
  - |
    # Test the master branch with Nim master and other branches with Nim devel
    if [ "$TRAVIS_BRANCH" = master ]; then
        export branch=master
    else
        export branch=devel
    fi
install:
  - |
    git clone -b $branch --depth 1 git://github.com/nim-lang/nim nim-$branch/
    cd nim-$branch
    git clone -b $branch --depth 1 git://github.com/nim-lang/csources csources/
    cd csources
    sh build.sh
    cd ..
    rm -rf csources
    bin/nim c koch
    ./koch boot -d:release
    cd ..
before_script:
  - export PATH="nim-$branch/bin:$PATH"
script: nim c --run ./tests/test.nim